### ISSUE TITLE
Badge counter doesn't update after messages are read

### ISSUE THREAD

**Issue by antoniodesousa** [aberonni/gmail-app-badge-notification#2]
Hi,

The badge counter seems to work fine in general but it doesn't update the count when you read one of the new messages.
So, you get 2 emails and they are new, the badge does show 2 unread messages, but after I read those emails it still shows 2 instead of 0 or no badge. I have to close the app and start it again for it to work.

**Comment by aberonni** [comment]
Does it never update once you open the app? What about if you just read one email? This is quite odd, but I suspect it has something to do with the caching mechanism. What OS are you on?

**Comment by antoniodesousa** [comment]
hmm for some reason, it does update now when I read an email but the counter never goes lower than 1. I need to close the app for it to reset. Strange, it wasn't updating before...

Something that I find annoying too, it's that the counter also counts emails in my social and promotions folders. I would like to know only how many new emails I have in my primary inbox. If I hover the Gmail icon in my taskbar, the app shows the correct number, like the app shows Inbox (2) but the badge shows 3 because it counts 1 email from my socials folder.

Windows 10 Enterprise 1909
Microsoft Edge Version 85.0.564.63 (Official build) (64-bit) (Chromium)

**Comment by aberonni** [comment]
> hmm for some reason, it does update now when I read an email but the counter never goes lower than 1. I need to close the app for it to reset. Strange, it wasn't updating before...

I just tested on a machine with Windows 10 and it seems to be working as expected. I would recommend checking if you have any chrome updates pending seeing as the gmail app will rely on chrome. If that doesn't work, you can load the unpacked extension into your instance of chrome and try debugging the code to see what is going on.

> Something that I find annoying too, it's that the counter also counts emails in my social and promotions folders. I would like to know only how many new emails I have in my primary inbox. If I hover the Gmail icon in my taskbar, the app shows the correct number, like the app shows Inbox (2) but the badge shows 3 because it counts 1 email from my socials folder.

Makes sense, although I'm guessing that some people would prefer to have the total unread (not sure because I don't use social and promotions folders) so ideally this should be configurable somehow. I don't really have time to tackle this but would be happy to look at an PR that does if you want to give it a go.
